### ISSUE TITLE
Possible factor-of-4 error for byte-related stats

### ISSUE THREAD

**Issue by welhpc** [vault/scc-harrier-ansible#1]
Hi,
   I'm not sure if this has always been the case, but from the man page for the infiniband 'perfquery' command (upon which the ib_perf.py script relies), it says this:

    Note: In PortCounters, PortCountersExtended, PortXmitDataSL, and PortRcvDataSL, components that represent Data (e.g. PortXmitData and PortRcvData) indicate octets divided by 4 rather than just octets.

I've verified that this is indeed what it shows on my system; I believe that ib_perf.py needs to multiply rxbytes and txbytes  by 4 (in the get_ib_stats function).

**Comment by vault** [comment]
You're probably right. I can't find the script I based this off of anymore, so I'm not sure if that's my fault for deleting something I didn't understand, or if the original script also had that problem.

This is probably moot though, since it seems like ganglia actually has infiniband support included in gmond upstream now. ([See here.](https://github.com/ganglia/gmond_python_modules/tree/master/network/infiniband) It already [multiplies by 4](https://github.com/ganglia/gmond_python_modules/blob/master/network/infiniband/python_modules/infiniband.py#L453).)

I'm going to close this since this solution seems obsolete and I'm not in a position to test any fixes. If you're relying on this repository for a cluster config I'd recommend working off your own fork and applying this fix there.
